[package]
name = "micro_traffic_sim_core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
lazy_static = "1.5.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "shortest_path_benchmark"
harness = false
